Update IntegrationConfig related docs
stakater/mto-docs pull request #101
Opened 2024-01-31 06:11 UTC by SheryarButt

2024-02-14 15:48 UTC, tanalam2411 requested changes

2024-02-14 15:48 UTC, tanalam2411 commented on content/reference-guides/integrationconfig.md
> +    vault:
The vault doesnt seems updated with the latest IC changes.

2024-02-14 17:24 UTC, SheryarButt commented on content/reference-guides/integrationconfig.md
> +    vault:
This one is according to the use case only. 
The complete yaml is in the integration-config.md

2024-02-15 05:21 UTC, SheryarButt commented on content/reference-guides/integrationconfig.md
> +    vault:
Updated

2024-03-11 13:55 UTC, merged