Adding stakater-docs-mkdocs-theme submodule to mto-docs
stakater/mto-docs pull request #97
Opened 2024-01-03 16:20 UTC by ufateh

We have derived common mkdocs theme to a separate project and now we are adding it as a sub module to mto-docs project. 

Changes should reflect as:

1. After deploying, we should see theme option in the headerbar, light, dark and auto select theme options.
2. On selecting light theme, we have a colours according to our main site theme.
3. on selecting dark theme, we will see dark background and other colours according to Stakater main site.

Dockerfile has been changed as well.

2024-01-05 08:52 UTC, ufateh commented on .github/workflows/push.yaml
> +      - name: Install mike
new step

2024-01-05 08:52 UTC, ufateh commented on .github/workflows/push.yaml
> +        run: |
another new step

2024-01-05 08:53 UTC, ufateh commented on .vale.ini
>  MinAlertLevel = warning
removed existing vocabulary and using the one packaged with common theme repo

2024-01-05 08:54 UTC, ufateh commented on content/faq.md
> +**Answer.** OpenShift recently updated its process of handling SCC, and it's now managed by annotations like `openshift.io/sa.scc.uid-range` on the namespaces. Absence  of them wont let pods schedule
fixed issue with current main branch, a reference was bad

2024-01-05 08:55 UTC, ufateh commented on prepare_theme.sh
> +python theme_common/scripts/combine_mkdocs_config_yaml.py theme_common/mkdocs.yml theme_override/mkdocs.yml mkdocs.yml
we should have this script in each mkdocs project, it will run the scripts from mkdocs stakater theme repository

2024-01-05 13:06 UTC, karl-johan-grahn requested changes

2024-01-05 13:06 UTC, karl-johan-grahn commented on .github/workflows/closed_pr.yaml
> +    uses: stakater/.github/.github/workflows/mkdocs_pull_request_closed.yaml.yaml@v0.0.60
redundant `.yaml` at end of reference

2024-01-05 13:06 UTC, karl-johan-grahn commented on .github/workflows/pull_request.yaml
> +      # below context not needed
remove it if no longer needed

2024-01-05 13:06 UTC, karl-johan-grahn commented on .github/workflows/release.yaml
> +      # below context not needed
remove if no longer needed

2024-01-05 13:06 UTC, karl-johan-grahn commented on .gitmodules
> +	url = https://github.com/stakater/stakater-docs-mkdocs-theme.git
why https and not git?

2024-01-05 13:06 UTC, karl-johan-grahn commented on Dockerfile
> +RUN mkdocs build
is this needed? the way mike works, it builds the output in the gh-output folder

2024-01-05 13:27 UTC, ufateh commented on .gitmodules
> +	url = https://github.com/stakater/stakater-docs-mkdocs-theme.git
i am not totally sure about this. With https, you have to provide the github access token, whereas i have noticed with git protocol, you have to setup SSH key pair to clone the repo locally.

2024-01-05 13:32 UTC, ufateh commented on Dockerfile
> +RUN mkdocs build
we created this dockerfile because otherwise it was not possible to build a docker container locally.
Mike will put the new version in gh-pages due to the fact that our github workflow is setup that way.
One thing i am not sure about is are we using this docker image for deployment or the gh-pages branch via github?

2024-01-07 20:02 UTC, karl-johan-grahn approved these changes

2024-01-07 20:02 UTC, merged